title: Cedar Zeng's Homepage
page-top-title: Cedar Zeng
top-section-bg-text: Data Mining, Multimodal Intelligence, LLM Agents
home-subtitle: Cedar Zeng&ensp;|&ensp;Computer Science Undergraduate
copyright-text: '&copy; Cedar Zeng 2026. All Rights Reserved.'
